### ISSUE TITLE
Issue with Undo a Missing Pallet after Undo Relocated 

### ISSUE THREAD

**Issue by seoul-hatiolab** [things-factory/opa-app#24]
Some case I try for CC just now

Pallet A: Steps:
1. Go mising pallet
2. Relocate new location
3. undo relocated
4. undo missing pallet
5. Error : error [GraphQL error]: Message: Cannot read property 'targetInventory' of undefined, Location: [object Object], Path: undoInspection

**Comment by horwengliang95** [comment]
Missing pallet will need to undergo relocate instead of using undo
