### ISSUE TITLE
Issue with inventories / pallet doensn't appeared after click "Reject" button

### ISSUE THREAD

**Issue by seoul-hatiolab** [things-factory/opa-app#25]
Another case I try for CC just now
Customer just have One pallet, you can try Kimeda Customer named Grace:

Pallet A: Steps:
1. Go mising pallet
2. Relocate new location
3. GO cycle count listing. Get no tally result
4. Click Reject the cycle count to create new
5. No pallet appear?

**Comment by horwengliang95** [comment]
No issue from dev test
